# ✅ Build Configuration
[build]
  command = "npm run build"
  publish = "dist"

# ✅ Ensure Node.js is Up-to-Date
[build.environment]
  NODE_VERSION = "22"

# ✅ Redirect API requests correctly (fixes 404s for API routes)
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true

# ✅ Ensure SSR Pages Load Properly
[[redirects]]
  from = "/ssr/*"
  to = "/.netlify/functions/entrypoint"
  status = 200
  force = false

# ✅ Ensure Netlify Serves Static Pages Properly
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

# ✅ Optimize Netlify Functions
[functions]
  node_bundler = "esbuild"

# ✅ Route All SSR Requests to Edge Functions
[[edge_functions]]
  function = "entrypoint"
  path = "/*"
  
// let's go.