[build]
  command = "npm run build"
  functions = "netlify/functions"  # Ensures SSR works

[build.environment]
  NODE_VERSION = "22"  # Upgraded to Node 20 for compatibility

[functions]
  node_bundler = "esbuild"

# Route API requests correctly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Catch-all route for SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entrypoint"
  status = 200
  force = true

# Cache optimization
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"