# ✅ Build Configuration
[build]
  command = "npm run build"
  publish = "dist"

# ✅ Ensure Node.js is Up-to-Date
[build.environment]
  NODE_VERSION = "22"

# ✅ Redirect API requests correctly (fixes 404s for API routes)
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true

# ✅ Ensure SSR pages work (fixes 404s for dynamic routes)
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true

# ✅ Optimize Netlify Functions
[functions]
  node_bundler = "esbuild"

# ✅ Route All SSR Requests to Edge Functions
[[edge_functions]]
  function = "entrypoint"
  path = "/*"
